[platformio]
default_envs = sparkfun_c6

[env:sparkfun_c6]
platform = https://github.com/pioarduino/platform-espressif32/releases/download/55.03.311/platform-espressif32.zip
board = sparkfun_esp32c6_thing_plus
framework = arduino
board_build.partitions = default_16MB.csv
monitor_speed = 115200
upload_speed = 460800
build_flags =
    -DCORE_DEBUG_LEVEL=0
lib_deps =
    bblanchon/ArduinoJson @ ^7
    https://github.com/tzapu/WiFiManager.git
    https://github.com/sparkfun/SparkFun_VL53L5CX_Arduino_Library.git
    https://github.com/adafruit/Adafruit_Si7021.git
    https://github.com/adafruit/Adafruit_Sensor.git
    https://github.com/sparkfun/SparkFun_BMA400_Arduino_Library.git
    https://github.com/sparkfun/SparkFun_MAX1704x_Fuel_Gauge_Arduino_Library.git
    adafruit/Adafruit EPD @ ^4.6.11
